openapi: 3.0.1
info:
  title: animals
  description: list of animals
  version: '0.1'
servers:
  - url: 'http://animals:8080'
paths:
  /animals:
    get:
      description: List all animals
      operationId: listAnimals
      responses:
        '200':
          description: a list of animals with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Animals"
              #examples: {"adjectives": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://animals:8080'
    post:
      description: create a animal
      operationId: createAnimal
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
            examples:
              '0':
                value: '{"name":"yellow"}'
              '1':
                value: '{"id":4}'
      responses:
        '201':
          description: animal created
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://animals:8080'
    delete:
      description: delete a animal
      operationId: deleteAnimal
      responses:
        '404':
          description: Auto generated using Swagger Inspector
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://animals:8080'
    servers:
      - url: 'http://animals:8080'
  /animals/{id}:
    get:
      description: get a specific animal
      operationId: showAnimalById
      parameters:
        - name: id
          in: path
          required: true
          description: id of the animal to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Animal"
              # examples: {"adjectives": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://animals:8080'
        
components:
  schemas:
    Animal:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  #      tag:
  #        type: string
    Animals:
      type: array
      items:
        $ref: "#/components/schemas/Animal"
