openapi: 3.0.1
info:
  title: locations
  description: list of locations
  version: '0.1'
servers:
  - url: 'http://locations:8080'
paths:
  /locations:
    get:
      description: List all locations
      operationId: listLocations
      responses:
        '200':
          description: a list of locations with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Locations"
              #examples: {"locations": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://locations:8080'
    post:
      description: create a location
      operationId: createLocation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
            examples:
              '0':
                value: '{"name":"yellow"}'
              '1':
                value: '{"id":4}'
      responses:
        '201':
          description: location created
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://locations:8080'
    delete:
      description: delete a location
      operationId: deleteLocation
      responses:
        '404':
          description: Auto generated using Swagger Inspector
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://locations:8080'
    servers:
      - url: 'http://locations:8080'
  /locations/{id}:
    get:
      description: get a specific location
      operationId: showLocationById
      parameters:
        - name: id
          in: path
          required: true
          description: id of the location to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Location"
              # examples: {"adjectives": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://locations:8080'
        
components:
  schemas:
    Location:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  #      tag:
  #        type: string
    Locations:
      type: array
      items:
        $ref: "#/components/schemas/Location"
