openapi: 3.0.1
info:
  title: adjectives
  description: list of adjectives
  version: '0.1'
servers:
  - url: 'http://adjectives.api:8080'
paths:
  /adjectives:
    get:
      description: List all adjectives
      operationId: listAdjectives
      responses:
        '200':
          description: a list of adjectives with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Adjectives"
              #examples: {"adjectives": [{"id":1,"name":"kind"}]}
      servers:
        - url: 'http://adjectives.api:8080'
    post:
      description: create an adjectives
      operationId: createAdjective
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
            examples:
              '0':
                value: '{"name":"kind"}'
              '1':
                value: '{"id":4}'
      responses:
        '201':
          description: adjective created
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://adjectives.api:8080'
    delete:
      description: delete a adjective
      operationId: deleteAdjective
      responses:
        '404':
          description: Auto generated using Swagger Inspector
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://adjectives.api:8080'
    servers:
      - url: 'http://adjectives:8080'
  /adjectives/{id}:
    get:
      description: get a specific adjective
      operationId: showAdjectiveById
      parameters:
        - name: id
          in: path
          required: true
          description: id of the adjective to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Adjective"
              # examples: {"adjectives": [{"id":1,"name":"kind"}]}
      servers:
        - url: 'http://adjectives.api:8080'
        
components:
  schemas:
    Adjectives:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  #      tag:
  #        type: string
    Adjectives:
      type: array
      items:
        $ref: "#/components/schemas/Adjectives"
