---
apiVersion: v1
kind: Service
metadata:
  name: generator
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: generator
  template:
    metadata:
      labels:
        name: generator
    spec:
      containers:
      - name: generator
        image: registry.gitlab.com/sentence-application/generator/volterra-v0:dynamic
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: api
